[tool.poetry]
name = "swarmauri-community"
version = "0.5.1.dev8"
description = "This repository includes community components."
authors = ["Jacob Stewart <jacob@swarmauri.com>"]
license = "Apache-2.0"
readme = "README.md"
repository = "http://github.com/swarmauri/swarmauri-sdk"
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12"
]

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
beautifulsoup4 = "04.12.3"
captcha = "*"
chromadb = "*"
duckdb = "*"
folium = "*"
gensim = "*"
google-generativeai = "*"
gradio = "*"
leptonai = "0.22.0"
neo4j = "*"
nltk = "*"
numpy = "*"
openai = "^1.52.0"
pandas = "*"
psutil = "*"
pydantic = "*"
pygithub = "*"
python-dotenv = "*"
qrcode = "*"
redis = "^4.0"
requests = "*"
scikit-learn="^1.4.2"
swarmauri = ">=0.5.0"
textstat = "*"
transformers = ">=4.45.0"
typing_extensions = "*"

# Pacmap requires specific version of numba
#numba = ">=0.59.0"
#pacmap = "==0.7.3"



[tool.poetry.dev-dependencies]
flake8 = "^7.0"  # Add flake8 as a development dependency
pytest = "^8.0"  # Ensure pytest is also added if you run tests
pytest-asyncio = ">=0.24.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
norecursedirs = ["combined", "scripts"]

markers = [
    "test: standard test",
    "unit: Unit tests",
    "integration: Integration tests",
    "acceptance: Acceptance tests",
    "experimental: Experimental tests",
]

log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)s] %(message)s"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"

asyncio_default_fixture_loop_scope = "function"
