name: Parse Feature Request

on:
  issues:
    types:
      - opened

jobs:
  parse-feature-request:
    runs-on: ubuntu-latest

    steps:
      - name: Log Issue Body
        run: |
          echo "Issue Body:"
          echo "${{ github.event.issue.body }}"

      - name: Parse Feature Request Details
        id: parse-details
        run: |
          issue_body="${{ github.event.issue.body }}"

          # Parse fields from the issue body
          feature_name=$(echo "$issue_body" | sed -n '/### Feature Name/{n;p}' | xargs)
          feature_description=$(echo "$issue_body" | sed -n '/### Feature Description/{n;p}' | xargs)
          motivation=$(echo "$issue_body" | sed -n '/### Motivation/{n;p}' | xargs)
          potential_solutions=$(echo "$issue_body" | sed -n '/### Potential Solutions/{n;p}' | xargs)
          impact_area=$(echo "$issue_body" | sed -n '/### Affected Areas/{n;p}' | xargs)
          priority=$(echo "$issue_body" | sed -n '/### Priority/{n;p}' | xargs)
          required_files=$(echo "$issue_body" | sed -n '/### Required Files/{n;p;n;p}' | xargs)

          echo "Feature Name: $feature_name"
          echo "Feature Description: $feature_description"
          echo "Motivation: $motivation"
          echo "Potential Solutions: $potential_solutions"
          echo "Impact Area: $impact_area"
          echo "Priority: $priority"
          echo "Required Files: $required_files"

          # Export parsed values as outputs
          echo "::set-output name=feature_name::$feature_name"
          echo "::set-output name=feature_description::$feature_description"
          echo "::set-output name=motivation::$motivation"
          echo "::set-output name=potential_solutions::$potential_solutions"
          echo "::set-output name=impact_area::$impact_area"
          echo "::set-output name=priority::$priority"
          echo "::set-output name=required_files::$required_files"

      - name: Display Parsed Values
        run: |
          echo "Feature Name: ${{ steps.parse-details.outputs.feature_name }}"
          echo "Feature Description: ${{ steps.parse-details.outputs.feature_description }}"
          echo "Motivation: ${{ steps.parse-details.outputs.motivation }}"
          echo "Potential Solutions: ${{ steps.parse-details.outputs.potential_solutions }}"
          echo "Impact Area: ${{ steps.parse-details.outputs.impact_area }}"
          echo "Priority: ${{ steps.parse-details.outputs.priority }}"
          echo "Required Files: ${{ steps.parse-details.outputs.required_files }}"
