name: Test Changed Files

on:
  push:
    paths:
      - 'pkgs/**'
  pull_request:
    paths:
      - 'pkgs/**'
  workflow_dispatch:

jobs:
  detect-changed-files:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.detect.outputs.matrix }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for proper diff

      - name: Detect changed files and map to tests
        id: detect
        run: |
          # Determine base branch and head branch
          BASE_BRANCH=${{ github.event.pull_request.base.ref }}
          HEAD_BRANCH=${{ github.event.pull_request.head.ref }}

          echo "Base branch: $BASE_BRANCH"
          echo "Head branch: $HEAD_BRANCH"

          # Fetch both branches
          git fetch origin $BASE_BRANCH
          git fetch origin $HEAD_BRANCH

          # Compare the source and target branches
          CHANGED_FILES=$(git diff --name-only origin/$BASE_BRANCH...origin/$HEAD_BRANCH | grep '^pkgs/')

          echo "Changed files:"
          echo "$CHANGED_FILES"

          # Initialize package and test map
          PACKAGE_TEST_MAP=""

          # Iterate through changed files
          for FILE in $CHANGED_FILES; do
            PACKAGE=$(echo "$FILE" | grep -oE '^pkgs/[^/]+' | cut -d/ -f2)
            COMPONENT_NAME=$(basename "$FILE" | sed 's/\.py$//')  # Extract the base name of the file without extension

            # Check if the file itself is a test file
            if echo "$FILE" | grep -qE '/tests/.*_test\.py$'; then
              # If it's a test file, map it directly to the matrix
              RELATIVE_TEST_FILE=$(echo "$FILE" | sed "s|^pkgs/$PACKAGE/||")  # Relative path from package root
              PACKAGE_TEST_MAP="$PACKAGE_TEST_MAP{\"package\":\"$PACKAGE\",\"test\":\"$RELATIVE_TEST_FILE\"},"
            else
              # If it's a source file, find corresponding test files
              TEST_DIR="pkgs/$PACKAGE/tests"  # Test directory for the package

              echo "Searching for test files related to: $COMPONENT_NAME in $TEST_DIR"

              # Search for test files recursively matching the component name
              if [ -d "$TEST_DIR" ]; then
                MATCHING_TEST_FILES=$(find $TEST_DIR -type f -iname "*${COMPONENT_NAME}*_test.py")
                echo "Matching test files: $MATCHING_TEST_FILES"

                for TEST_FILE in $MATCHING_TEST_FILES; do
                  RELATIVE_TEST_FILE=$(echo "$TEST_FILE" | sed "s|^pkgs/$PACKAGE/||")  # Relative path from package root
                  PACKAGE_TEST_MAP="$PACKAGE_TEST_MAP{\"package\":\"$PACKAGE\",\"test\":\"$RELATIVE_TEST_FILE\"},"
                done
              else
                echo "Warning: Test directory $TEST_DIR does not exist."
              fi
            fi
          done

          # Create JSON array for matrix
          if [ -z "$PACKAGE_TEST_MAP" ]; then
            MATRIX="[]"
          else
            MATRIX="[${PACKAGE_TEST_MAP%,}]"
          fi

          echo "Final test matrix: $MATRIX"
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

  run-tests:
    needs: detect-changed-files
    runs-on: ubuntu-latest
    if: needs.detect-changed-files.outputs.matrix != '[]'  # Skip if no tests to run
    strategy:
      fail-fast: false
      matrix:
        package_test: ${{ fromJSON(needs.detect-changed-files.outputs.matrix) }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV

      - name: Install package dependencies
        run: |
          cd pkgs/${{ matrix.package_test.package }}
          poetry install --no-cache -vv

      - name: Run specific tests
        run: |
          echo "Running tests for package: ${{ matrix.package_test.package }}"
          echo "Test file: ${{ matrix.package_test.test }}"
          cd pkgs/${{ matrix.package_test.package }}
          poetry run pytest ${{ matrix.package_test.test }}
